### ISSUE TITLE
Contributor count broken

### ISSUE THREAD

**Issue by samcaulfield** [mereckaj/PML-IDE#27]
It seems that the contributor count for this repository is broken. The team responsible for this project has **5** members but it seems that only **4** contributors are displayed.

Steps to reproduce:

- Visit https://github.com/mereckaj/PML-IDE/graphs/contributors

- Only four contributors will be displayed, instead of the five that should be displayed.

**Comment by dariota** [comment]
Can confirm this bug is present on Firefox 45.0.1 on Windows 10, will confirm later on LMDE.
